// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAStUj4kMAjV4r16-gBT_ONK1oqdOq9jQ',
    appId: '1:1001157334736:web:ee6b148d4c39823e34f0d5',
    messagingSenderId: '1001157334736',
    projectId: 'spendsnap-b86a8',
    authDomain: 'spendsnap-b86a8.firebaseapp.com',
    storageBucket: 'spendsnap-b86a8.appspot.com',
    measurementId: 'G-MR59P74HT0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRMVcQAQysUZQXCdqU4ThOFKRPaLot6u0',
    appId: '1:1001157334736:android:ca9c28e34528b6ac34f0d5',
    messagingSenderId: '1001157334736',
    projectId: 'spendsnap-b86a8',
    storageBucket: 'spendsnap-b86a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7c_IRIzUtJND0sNs9LiN9VConX8MqX3U',
    appId: '1:1001157334736:ios:bcd4b24d3f18c40e34f0d5',
    messagingSenderId: '1001157334736',
    projectId: 'spendsnap-b86a8',
    storageBucket: 'spendsnap-b86a8.appspot.com',
    iosBundleId: 'com.example.firebasefluttter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeVtVc5kWI7TnS6s9jewGeXqYJIw-AvOs',
    appId: '1:204049094681:ios:a65376b6e11462d8bc3288',
    messagingSenderId: '204049094681',
    projectId: 'wybvehicals',
    storageBucket: 'wybvehicals.appspot.com',
    iosBundleId: 'com.example.firebasefluttter.RunnerTests',
  );
}